language: node_js
node_js:
  - 10

before_install:
  # Download latest yarn since travis defaults to v1.3.2
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --ignore-engines

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: release
      script:
        - npm run build
        - node node_modules/gh-pages/bin/gh-pages-clean
        - npm run gh-publish
      if: (NOT type IN (pull_request)) AND (branch = master)

stages:
  - name: release
